[package]
name = "ndarray-linalg-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linfa-linear = { git = "https://github.com/rust-ml/linfa" }
linfa = { git = "https://github.com/rust-ml/linfa" }
linfa-datasets = { git = "https://github.com/rust-ml/linfa",  features = ["diabetes"] }
