[package]
name = "ndarray-linalg-rs"
version = "0.1.0"
edition = "2018"
license = "MIT/Apache-2.0"

keywords = ["ndarray", "matrix"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
ndarray = { version = "0.15", default-features = false, features = ["approx"] }
num-traits = { version = "0.2.0" }
thiserror = { version = "1" }
